on: [push]

env:
  # personal accesss token with read access to public repos
  GIT_USER: rconybea
  GIT_ACCESS_TOKEN: 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

jobs:
  build_job:
    name: compile hello world, using prepared docker container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rconybea/docker-cpp-builder:v3
    steps:
      - name: ls /etc/ssl
        run:
          ls /etc/ssl

      - name: checkout
        run:
          # not using usual checkout action: bc complications from within container
          GIT_SSL_NO_VERIFY=true git clone https://${{env.GIT_USER}}:${{env.GIT_ACCESS_TOKEN}}@github.com/rconybea/docker-action-example3.git

      - name: ls -l
        run:
          ls -l
  
      - name: compile
        run:
          # make,g++ will run in container..
          make -C docker-action-example3

      - name: hello
        # need to use container for libc etc.
        run:
          ./docker-action-example3/hello Roland
          #${{github.workspace}}/hello Roland
